import '../global.css'

import Header from "@/components/layout/header"
import Footer from "@/components/layout/footer"

export const metadata = {
  title: 'PIT/RIT - IFCE Cedro',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="pt-br">
      <body>
        <Header/>
        <main className="app">
          <section className="content">{children}</section>
        </main>
      {/* <Footer/> */}
      </body>
    </html>
  )
}
